### ISSUE TITLE
Add additional variables which can be defined

### ISSUE THREAD

**Issue by ChrisHird** [Club-Seiden/RelicPackageManager#13]
Would like to have additional variables to allow the source to be kept separate from the build objects. &SRCLIB?

**Comment by WorksOfBarry** [comment]
Hi!

Additional variables sound like a good idea - but where would you define them? Within the build file? When calling `RELICGET`?

If you could provide examples, it would be much appreciated. :)

**Comment by ChrisHird** [comment]
Liam, I have not looked at your build file reader so not sure exactly what it does. I need additional variables to allow me to separate the source from the build objects (always a good idea) so having the ability to use relicget to read through the file and identify additional substitution variables would be useful.  I have done it before in PHP and C where I have a substitution marker such as #variable:value, when you read through the script you can find these and do a substitution directly in the read text or via the CL prompter API.

**Comment by WorksOfBarry** [comment]
Hi @ChrisHird 

How does this look for additional variables:
```
#srclib:ZLIBSRC
build:
  crtpgm src(&srclib/whatever) into(&srclib)
```

So any line that starts with `#` will be additional variable definition, and the value will be whatever is passed `:` and the name before it. You'd reference them like you would pre-defined variables.

Sound okay to you?

**Comment by ChrisHird** [comment]
@WorksOfBarry # is generally saved for comments, I would use &:value to fall in line with normal scripting.

**Comment by WorksOfBarry** [comment]
Hi @ChrisHird 

This functionality will be release with 0.006 of Relic - or you can `RELICGET` against the master of the repo to try it now.

I will now close this issue, thanks!
