### ISSUE TITLE
Allow Comments to be made in the build file

### ISSUE THREAD

**Issue by ChrisHird** [Club-Seiden/RelicPackageManager#15]
Need to have the ability to place comment lines in the build file so complex build scripts can be annotated to show the process and additional info. Could be useful when scripts go bad?

**Comment by ChrisHird** [comment]
Liam
I need to add the GNU license declaration to all the files so having the ability to use comments will be important, even in the build file. My suggestion is to use '/*' as the start of a comment line, any line with that is the first 2 places would be considered a comment? Allowing multi line comments etc could be a little challenging and we need to keep this pretty simple.

**Comment by WorksOfBarry** [comment]
Hi! I knew someone would ask this eventually.

Good point about the licence, I can make this a feature.

Proposed enhancement:
```
/* LICENCE TEXT
MORE TEXT BLAH */
//SOME COMMAND
version:
    //the version number
    5.0000

build:
    //DO MOVING PHASE
    SNDMSG MSG(HELLO) TOUSR(*REQUESTER)
    //ANOTHER COMMAND
```

Are these the type of comments you'd like to see @ChrisHird?

**Comment by bishbashbosh123** [comment]
Perhaps some sort of 'verbose output' option on the command could make the tool output every build line to the console before it runs that line?  To save having to add comments if you don't have any.

**Comment by ChrisHird** [comment]
Yep those will work for me

**Comment by WorksOfBarry** [comment]
HI @ChrisHird,

Commit 615649f5c22486b24a6af5d693470c03c71ff534 now contains the functionality to use comments within the build file. You can [read more on the wiki](https://github.com/Club-Seiden/RelicPackageManager/wiki/Getting-your-project-onto-GitHub#build-file-comments).

RPM 0.005 will contain this feature, or you can update your RPM against the master using `RELICGET PLOC('https://github.com/Club-Seiden/RelicPackageManager/archive/master.zip') PDIR('RelicPackageManager-master') PNAME(#RELIC)` to use it now.

I will now close this issue.
