### ISSUE TITLE
Idea: Advanced logging

### ISSUE THREAD

**Issue by starbuck5250** [Club-Seiden/RelicPackageManager#16]
Thomas Raddatz has written LOG4RPG which is similar to Log4j http://www.tools400.de/English/Freeware/Service_Programs/Log4rpg/log4rpg.html  Rather than use stdout to log errors, perhaps we could integrate Log4RPG and log to a stream file?

Alternatively, many RPG programmers naturally expect errors to be emitted to a spooled file.

This 'issue' is intended to spur discussion and ideas rather than be thought of as a demand for features.

**Comment by WorksOfBarry** [comment]
Perhaps logging the errors to a stream file might be better than displaying it on screen. Is this something you'd like to have optionally @starbuck5250?

**Comment by starbuck5250** [comment]
I do a small amount of work with Java and C.  As a result, I have environment variables set that redirect STDOUT elsewhere, and I tend to forget that until _after_ I've run RELICGET and something went casters up.  

In general, QSYS.LIB tools emit errors to a spool file; the RPG compiler is a good example.  PASE / stream file tools generally emit errors to STDOUT; GCC is a good example.  In the PASE world, it's easy enough to pipe stdout to a file and grep it, looking for... well, whatever.  In the QSYS.LIB world, it's easy to WRKSPLF and then use Find to locate... whatever.  RELICGET can't easily do either of those at the moment, which is not a complaint!  We're still early in the process, and adding features incrementally is absolutely a wonderful idea.

I was just thinking that one way to have RELICGET emit errors would be to make a stream file.  In terms of fostering discussion, the pros of this idea are that it gets RPG programmers thinking about the IFS on a very regular basis - something they'll want to do if they want to use 'regular' open source.  The cons are that RPG programmers rarely think about the IFS, and there's also the issue of cleaning up these temporary files.

I was sort of hoping more people would weigh in; perhaps the Gitter is a better place to talk about it?  I don't have a strong opinion one way or the other; I almost certainly would have created a spooled file out of sheer habit, but that's not a ringing endorsement as much as it is simple inertia.

**Comment by WorksOfBarry** [comment]
Hi @starbuck5250! I think logging to a stream file is a great idea. 

It'll be an extra optional parameter, perhaps something like `PLOG(*YES)` to log to a stream file - will default to `*NO`.

I'll start implementing it tomorrow and hope to have something committed by tomorrow night.

**Comment by WorksOfBarry** [comment]
Hi @starbuck5250 - this has now been implemented.

Development was done in a separate branch and has now been merged with commit 8a83baebc35e2095cb2693688687391979327828.

This has added a new parameter, `PLOG`, with the default of display `*DSP` and an option of `*STMF` streamfile.

Anything you'd like to add?

**Comment by WorksOfBarry** [comment]
Hi. This feature has now been released with Relic 0.005.

If there's still more you'd like to add, please let me know. Thanks!
