### ISSUE TITLE
Idea: Rebuild without re-download

### ISSUE THREAD

**Issue by starbuck5250** [Club-Seiden/RelicPackageManager#17]
When debugging `build.txt` it can be easier to modify the local, unzipped `build.txt` and then re-run the build portion as many times as it takes to debug the build script.  Currently, in order to debug the build script, one needs to run RELICGET on IBM i, then edit `build.txt` on Github, commit, and try again.  So, I'm thinking about an option that will allow me to execute the build portion of RELICGET without executing the download / unzip portion.

This has one other benefit.  Imagine a system that is denied access to the internet.  It would be possible to manually put the repo zip file in the IFS and then run the build portion without needing to reach out to the internet.

**Comment by WorksOfBarry** [comment]
So you're saying, create a RELICGET (for example) that doesn't require the internet so you're able to test the build file locally?

I'll stick it on my to do list. :+1:

**Comment by starbuck5250** [comment]
One thing I don't want to do is load you up with work.  I wanted to log the idea so that others could comment on it.  I'll be happy to add this functionality.  I was thinking about another parameter on the RELICGET command to default to the current behaviour (fetch and build) or optionally to build only.  Similar to Cygwin.

**Comment by WorksOfBarry** [comment]
You're more than welcome to add this new functionality (as long as it doesn't break how it currently works).

I'll add you to the contributors list so you can directly push to this repo.

Much appreciated @starbuck5250 !

**Comment by starbuck5250** [comment]
OK, so I popped it into master.  Give it a whirl and see how you like it.  I wasn't sure how to name the new parameter.'

```
RELICGET PLOC('https://github.com/Club-Seiden/RelicPackageManager/archive 
/master.zip') PDIR('RelicPackageManager-master') PNAME(RELICGET) 
```

On a somewhat related note, I really need to read up on Git and tags.

**Comment by WorksOfBarry** [comment]
Thanks Buck!

Would you mind updating the wiki with the new functionality? Either stick it on the linked page below or make a new page. 

https://github.com/Club-Seiden/RelicPackageManager/wiki/How-to-use-Relic

Cheers!

**Comment by WorksOfBarry** [comment]
Hi again, I made some basic syntax changes in commit dc5638628cd57ee7127701c3a97b2050f41f9623 - no changes.

Please just make sure you update the wiki!

**Comment by WorksOfBarry** [comment]
Buck, I have added stuff to the wiki about this feature here: https://github.com/Club-Seiden/RelicPackageManager/wiki/Getting-your-project-onto-GitHub#how-can-i-test-my-build-file

Please feel free to add more. You can close this when you feel it ready!

**Comment by WorksOfBarry** [comment]
Release 0.004 has come out of this bug, since it's now a stable version with new features.
