### ISSUE TITLE
RPG program RELIC s/b source type SQLRPGLE

### ISSUE THREAD

**Issue by starbuck5250** [Club-Seiden/RelicPackageManager#2]
I imported the package manager with RDi, iProjects, and eGit.  Created source members in QRPGLESRC and QCMDSRC: did not use a stream file.  When I tried to compile the RPG program, the compile failed.  I see that it's got embedded SQL.  The standard extension for embedded SQL is SQLRPGLE.  After I changed that, it compiled straight away.

**Comment by WorksOfBarry** [comment]
Okay. Tonight I will make the change to rename the extension. Thanks for bringing this up.

**Comment by WorksOfBarry** [comment]
Thanks again @starbuck5250 - this issue has now been resolved.
