### ISSUE TITLE
Document features

### ISSUE THREAD

**Issue by aaronbartell** [Club-Seiden/RelicPackageManager#21]
[This tweet](https://twitter.com/de__barry/status/744563926004817920) asked for new feature ideas.  I just reviewed the docs and am not seeing a features list.  Could one be added?

**Comment by WorksOfBarry** [comment]
HI @aaronbartell - thanks for raising this.

I've whipped up a list and linked it to other wiki pages. As a lot of the features are still being developed, I'll add them as I make commits to the repo.

Thanks,
Liam :smiley: 

https://github.com/Club-Seiden/RelicPackageManager/wiki/Current-features

**Comment by aaronbartell** [comment]
Looks great.  That's what I was hoping to see. Closing issue.
