### ISSUE TITLE
CMD has records past column 80

### ISSUE THREAD

**Issue by starbuck5250** [Club-Seiden/RelicPackageManager#3]
I used a source member to create the package manager and the command would not compile on my 7.2 system because there were several records extending beyond column 80.  Splitting the long lines onto multiple physical lines fixed that.

**Comment by WorksOfBarry** [comment]
Good find, I'll investigate tonight, cut the lines down and commit any changes.

Thanks!

**Comment by WorksOfBarry** [comment]
@starbuck5250 Just looked at the source member in RDi.. seems I am not having the same length of the CMD.

Could it be because I am using a record length of 112?

**Comment by starbuck5250** [comment]
Probably.  My QCMDSRC is old, and only 92.  It's not that easy to change it to 112; it requires creating a new SRCPF and copying all the members over.  Which changes the 'last used' date, which confuses other programmers into thinking the source was recently changed.

**Comment by WorksOfBarry** [comment]
No problem.

I'll create a new QCMDSRC with the shorter length and push the changes for you tonight. :+1:

**Comment by starbuck5250** [comment]
No rush - the only reason I opened this is that we're looking for the broadest possible acceptance 'out there'. :-)  You're a true asset to the community!

**Comment by WorksOfBarry** [comment]
Hi,

In commit 919c689037a41d1c825a9b29d8597be75e77aac3 this issue has been addressed.

I created a new SPF with a length of 92 and RELICGET.CMD is now the result of a shorter record length.

Thanks,
Liam
