### ISSUE TITLE
Push disabled for the repository

### ISSUE THREAD

**Issue by ChrisHird** [Club-Seiden/RelicPackageManager#30]
Liam, tried to push a commit for a new CLP I have built to allow the objects to be compiled as a single operation. Not Allowed! Cant collaborate unless we can push changes. Also need to think about how we want to have new branches etc and what kind of change requires a new branch as opposed to a commit to the master.
Chris

**Comment by WorksOfBarry** [comment]
Hi. 

I can add you as a contributor now - usually you'd make a pull request with a change but I don't mind you having direct write-access.

I have sent you an email with a link that you will need to accept to have write-access, then try and commit+push your changes and it should work fine.

**Comment by WorksOfBarry** [comment]
Read about pull-requests here: https://help.github.com/articles/creating-a-pull-request/
