### ISSUE TITLE
Install issues with RELICGET

### ISSUE THREAD

**Issue by andrescolodrero** [Club-Seiden/RelicPackageManager#31]
Hi,
im having this problem:
RELICGET  PLOC('https://github.com/Club-Seiden/RelicPackageManager/archive 
/0.006.zip') PDIR('RelicPackageManager-0.006') PNAME('#RELIC')             
User-defined function error on member SYSDUMMY1.                           
User-defined function error on member SYSDUMMY1.                           
Java stored procedure or user-defined function SYSTOOLS.HTTPGETBLOB,       
  specific name HTTPG00001 aborted with an exception                       
  "com.ibm.db2.rest.HttpUDFException".                                     

Not sure if this is due to proxy settings or not.

I guess is just fine copy&paste code and compile

**Comment by WorksOfBarry** [comment]
HI!

Thanks for showing interest in this! :smile: 

What version of IBM i are you on? 

It may be possible that you aren't up to date with some of your PTFs (DB2 PTFs to be precise).

**Comment by andrescolodrero** [comment]
HI,
Im on 7.2 latest PTF... i believe this is a proxy problem.
I have been trying to setup java properties, but doesnt work.

I get all source code and i compile it. But the SYNC program is creating the /home/user/LIBNAME/FILENAME,, but empty. ALso, it is not creating the source of programs.


I guess i forget something in the install... can i do a manual install with the zip file?

**Comment by WorksOfBarry** [comment]
Hi!

If you're just trying to install the package manager, it sounds like you've done it.

The SYNC tool is used for moving your source from source members to the IFS - is this what you're trying to do? What does the SYNC command you're using look like?

**Comment by andrescolodrero** [comment]
CALL SYNC '#RELIC'
Press ENTER to end terminal session. 
Getting #RELIC/EVFEVENT..            
> RELIC     ...completed             
Getting #RELIC/EVFTEMPF01..          
Getting #RELIC/EVFTEMPF02..          
Getting #RELIC/QSOURCE..             
Press ENTER to end terminal session. 

I check some errors and... i just need to compile with commit *none :)

it works.

**Comment by WorksOfBarry** [comment]
Haha, glad it's working! 

May I ask what you're planning to do with the package manager? You should also [check out the wiki ](https://github.com/Club-Seiden/RelicPackageManager/wiki )if you ever get stuck - or you can email me, or raise more issues :smile:

**Comment by andrescolodrero** [comment]
Yes, of course.

Im checking the use of SYNC to migrate legacy RPG code/CLP and send it to git.
I have dev/test/prod enviroments and i use a propietary system for life cycle management.

I´d like to be able to set push code to Git, and deploy on test and production.
Let says:

Git contains all source code.
git clone/pull -> set the user source file on DEV machine.
sync the IFS with source member(for non free rpg code).
sync the member with IFS after compile.
Git push.

And then.
git pull/clone into test. Compile and test. (or send the objetcs).
git pull/clone into prod. Compile on prod.

My only concern is to check the status of each source code (what is on dev, prod, or test).
